baseURL = "https://www.webdevelopment2.com/"
languageCode = "en-us"
paginate = "8" # Number of posts per page
title = "Web Development 2.0: Web Design, ASP.NET Core, CakePHP, Javascript"
theme = "bookworm-light"
description = "Quick and Dirty Web Development"

summaryLength = "45"
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4

disqusShortname = "webdevelopment2" # Enable Disqus comments by entering your Disqus shortname
googleAnalytics = "UA-100181-5" # Enable Google Analytics by entering your tracking id
enableRobotsTXT = true

# [Author] # Used in authorbox
#   name = "John Doe"
#   bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
#   avatar = "img/avatar.png"

[permalinks]
  post = "/:title/"
  blog = "/:title/"

# [markup.goldmark.renderer]
#   unsafe= false

# [Params]
#   description = "Quick and Dirty Web Development" # Site description. Used in meta description
#   copyright = "Web Development 2.0" # Footer copyright holder, otherwise will use site title
#   opengraph = true # Enable OpenGraph if true
#   schema = true # Enable Schema
#   twitter_cards = true # Enable Twitter Cards if true
#   readmore = true # Show "Read more" button in list if true
#   authorbox = false # Show authorbox at bottom of pages if true
#   toc = true # Enable Table of Contents
#   pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
#   post_meta = ["date", "categories", "translations"] # Order of post meta information
#   mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
#   dateformat = "Mon Jan 2, 2006" # Change the format of dates
#   mathjax = false # Enable MathJax
#   mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
#   mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
#   customCSS = ["css/custom.css"] # Include custom CSS files
# #   customJS = ["js/custom.js"] # Include custom JS files

# [Params.style.vars]
#   highlightColor = "#e22d30" # Override highlight color
#   # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
#   # Take care of different quotes OR escaping symbols in these params if necessary
#   fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
#   fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

# [Params.logo]
#   #image = "img/placeholder.png" # Logo image. Path relative to "static"
#   # title = "Mainroad" # Logo title, otherwise will use site title
#   subtitle = "Quick and Dirty Web Development" # Logo subtitle

# [Params.sidebar]
#   home = "right" # Configure layout for home page
#   list = "right"  # Configure layout for list pages
#   single = "right" # Configure layout for single pages
#   # Enable widgets in given order
#   widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

# [Params.thumbnail]
#   visibility = ["list", "post"] # Control thumbnail visibility 

# [Params.widgets]
#   recent_num = 5 # Set the number of articles in the "Recent articles" widget
#   categories_counter = true # Enable counter for each category in "Categories" widget
#   tags_counter = true # Enable counter for each tag in "Tags" widget

# [Params.widgets.social]
# #   # Enable parts of social widget
# #   facebook = "username"
#   twitter = "kevinlloyd749"
# #   instagram = "username"
# #   linkedin = "username"
# #   telegram = "username"
#   github = "lloydkevin"
# #   gitlab = "username"
# #   bitbucket = "username"
# #   email = "example@example.com"

# # # Custom social links
# # [[Params.widgets.social.custom]]
# #   title = "Youtube"
# #   url = "https://youtube.com/user/username"
# #   icon = "youtube.svg" # Optional. Path relative to "layouts/partials"

# # [[Params.widgets.social.custom]]
# #   title = "My Home Page"
# #   url = "http://example.com"

############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.87.0"

############################# Image Processing ##############################
[imaging]
quality = "95"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true


############################## Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Mulish:wght@500;600;700;800;900&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/instagram-feed/instagram-feed.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# site variables
[params.variables]
font_primary = "Mulish"
h1 = "64px"
h1_lg = "52px"
h1_md = "42px"
h2 = "38px"
h2_md = "30px"
h3 = "30px"
h3_md = "24px"
h4 = "24px"
h5 = "18px"
h6 = "16px"
white = "#ffffff"
black = "#000000"
dark = "#152035"
gray = "#747577"
light = "#FAFAFA"
color_primary = "#01AD9F"

#################### default parameters ################################
[params]
logo = "images/logo.png"
# logo_width = "200px"
# favicon = "images/favicon.png"
# Meta data
description = "Quick and Dirty Web Development"
author = "Kevin Lloyd"
logo_text = "Web Development 2"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true
# main section
mainSections = ["blog"]
# copyright
copyright = "Designed & Developed By [Gethugothemes](https://gethugothemes.com/)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Instagram feed
[params.instafeed]
enable = false
instagram_user = "bookworm"
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours
title = "Subscribe for our monthly newsletter."
input_placeholder = "Enter your email"

# cookies
[params.cookies]
enable = false
expire_days = 2


############################# Main Menu ########################
[[menu.main]]
name = "Home"
url = "/"
weight = 1
  
[[menu.main]]
name = "About"
url = "about/"
weight = 3
  
[[menu.main]]
name = "Portfolio"
url = "/portfolio/"
weight = 4
  
[[menu.main]]
name = "Personal"
url = "https://www.kevinlloyd.net/"
weight = 5

# [[menu.main]]
# weight = 6
# url = "#"
# name = "Pages"
# hasChildren = true

#   [[menu.main]]
#   parent = "Pages"
#   name = "Author"
#   url = "author/"
#   weight = 1
  
#   [[menu.main]]
#   parent = "Pages"
#   name = "Tags"
#   url = "tags/"
#   weight = 2
  
#   [[menu.main]]
#   parent = "Pages"
#   name = "Category"
#   url = "categories/"
#   weight = 3
  
#   [[menu.main]]
#   parent = "Pages"
#   name = "Elements"
#   weight = 4
#   url = "elements/"
  
#   [[menu.main]]
#   parent = "Pages"
#   name = "Privacy"
#   url = "privacy/"
#   weight = 5
  
#   [[menu.main]]
#   parent = "Pages"
#   name = "Terms & Conditions"
#   url = "terms-conditions/"
#   weight = 6

############################# Footer Menu ########################
[[menu.footer]]
name = "About"
url = "about/"
weight = 1

[[menu.footer]]
name = "Portfolio"
url = "portfolio/"
weight = 2

# [[menu.footer]]
# name = "Privacy"
# url = "privacy/"
# weight = 3

# [[menu.footer]]
# name = "Terms & Conditions"
# url = "terms-conditions/"
# weight = 4

# Social Icons
# [[params.social]]
# icon = "lab la-facebook-f" # https://icons8.com/line-awesome
# url = "https://www.facebook.com/"

[[params.social]]
icon = "lab la-github" # https://icons8.com/line-awesome
url = "https://www.github.com/lloydkevin"

[[params.social]]
icon = "lab la-twitter" # https://icons8.com/line-awesome
url = "https://www.twitter.com/kevinlloyd749"

# [[params.social]]
# icon = "lab la-instagram" # https://icons8.com/line-awesome
# url = "https://www.instagram.com/"

# [[params.social]]
# icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
# url = "https://www.linkedin.com/"