url: https://webdevelopment2.com
name: 'Web Development 2.0: Web Design, ASP.NET MVC, CakePHP, Javascript'
description: 'Quick and Dirty Web Development for Web 2.0: ASP.NET MVC, CakePHP, JQuery, and lots more.'
